name: prism
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/tiagohm/prism

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
