name: prism
description: Dart Syntax Highlighter.
version: 0.0.1
author: tiagohm <tiago.henrique.cco@gmail.com>
homepage: https://github.com/tiagohm/prism

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  test: